import PDFDocument from "pdfkit";
import { getInvoice } from "@/lib/billing/invoice-repository";
import { getOrgProfile } from "@/lib/settings/org-repository";
import { apiError } from "@/lib/api-response";

export const dynamic = "force-dynamic";

function buildInvoicePdf(input: {
  orgName: string;
  gstin: string;
  number: string;
  client: string;
  due: string;
  status: string;
  lineItems: { description: string; amount: string }[];
  subtotalInr: number;
  gst: string;
  amount: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).text(input.orgName, { continued: false });
    doc
      .fontSize(10)
      .fillColor("#555555")
      .text(`GSTIN ${input.gstin} · Tax invoice`);
    doc.moveDown();
    doc.fillColor("#000000").fontSize(16).text(input.number);
    doc
      .fontSize(11)
      .text(`Bill to: ${input.client}`)
      .text(`Due: ${input.due}`)
      .text(`Status: ${input.status}`);
    doc.moveDown();

    doc.fontSize(11).text("Description", 50, doc.y, { continued: true, width: 350 });
    doc.text("Amount", { align: "right" });
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    for (const line of input.lineItems) {
      const y = doc.y;
      doc.text(line.description, 50, y, { width: 350 });
      doc.text(line.amount, 400, y, { width: 145, align: "right" });
      doc.moveDown(0.4);
    }

    doc.moveDown();
    doc.text(`Subtotal · ₹${input.subtotalInr.toLocaleString("en-IN")}`, {
      align: "right",
    });
    doc.text(`GST (18%) · ${input.gst}`, { align: "right" });
    doc.fontSize(12).text(`Total · ${input.amount}`, { align: "right" });
    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#888888")
      .text("Generated by ZAFTYS TSM", { align: "left" });

    doc.end();
  });
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const [invoice, org] = await Promise.all([getInvoice(id), getOrgProfile()]);
  if (!invoice) return apiError("INVOICE_NOT_FOUND", "Invoice not found.", 404);

  const pdf = await buildInvoicePdf({
    orgName: org.name,
    gstin: org.gstin,
    number: invoice.number,
    client: invoice.client,
    due: invoice.due,
    status: invoice.status,
    lineItems: invoice.lineItems,
    subtotalInr: invoice.subtotalInr,
    gst: invoice.gst,
    amount: invoice.amount,
  });

  return new Response(new Uint8Array(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${invoice.number}.pdf"`,
      "Content-Length": String(pdf.length),
    },
  });
}
