import { getInvoice } from "@/lib/billing/invoice-repository";
import { getOrgProfile } from "@/lib/settings/org-repository";
import { apiError } from "@/lib/api-response";

export const dynamic = "force-dynamic";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const [invoice, org] = await Promise.all([getInvoice(id), getOrgProfile()]);
  if (!invoice) return apiError("INVOICE_NOT_FOUND", "Invoice not found.", 404);

  const lines = invoice.lineItems
    .map(
      (l) =>
        `<tr><td style="padding:8px;border-bottom:1px solid #ddd">${l.description}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">${l.amount}</td></tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${invoice.number}</title></head>
<body style="font-family:Segoe UI,Arial,sans-serif;max-width:720px;margin:40px auto;color:#1a1a1a">
  <h1 style="margin:0">${org.name}</h1>
  <p style="color:#555">GSTIN ${org.gstin} · Tax invoice (demo PDF)</p>
  <hr>
  <h2>${invoice.number}</h2>
  <p>Bill to: <strong>${invoice.client}</strong><br>Due: ${invoice.due}<br>Status: ${invoice.status}</p>
  <table style="width:100%;border-collapse:collapse;margin-top:24px">
    <thead><tr><th style="text-align:left;padding:8px;border-bottom:2px solid #333">Description</th><th style="text-align:right;padding:8px;border-bottom:2px solid #333">Amount</th></tr></thead>
    <tbody>${lines}</tbody>
  </table>
  <p style="text-align:right;margin-top:16px">Subtotal · ₹${invoice.subtotalInr.toLocaleString("en-IN")}<br>
  GST (18%) · ${invoice.gst}<br>
  <strong>Total · ${invoice.amount}</strong></p>
  <p style="color:#888;font-size:12px;margin-top:48px">Generated by ZAFTYS TSM · local demo export</p>
</body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${invoice.number}.html"`,
    },
  });
}
