/**
 * Lorry Receipt (LR) PDF — ADR-009 v1.
 * Printable A4 from a TSM shipment; no Fleetbase dependency.
 */

import PDFDocument from "pdfkit";
import type { ShipmentRecord } from "@/lib/dev-store";

export type LrPdfOrg = {
  name: string;
  gstin?: string;
  address?: string;
};

export type LrPdfResult = {
  buffer: Buffer;
  lrNumber: string;
  filename: string;
};

export function buildLrPdf(
  shipment: ShipmentRecord,
  org: LrPdfOrg,
  opts?: { lrNumber?: string },
): Promise<LrPdfResult> {
  const lrNumber =
    opts?.lrNumber?.trim() ||
    shipment.lrNumber?.trim() ||
    `LR-${new Date().getFullYear()}-0000`;
  const filename = `${lrNumber.replace(/[^a-zA-Z0-9._-]+/g, "_")}.pdf`;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () =>
      resolve({
        buffer: Buffer.concat(chunks),
        lrNumber,
        filename,
      }),
    );
    doc.on("error", reject);

    const orgName = org.name?.trim() || "ZAFTYS TSM";
    doc.fontSize(18).fillColor("#0f1e3d").text(orgName, { continued: false });
    doc
      .fontSize(10)
      .fillColor("#555555")
      .text("Lorry Receipt (LR) · Generated by TSM");
    if (org.gstin) doc.text(`GSTIN ${org.gstin}`);
    if (org.address) doc.text(org.address);
    doc.moveDown(0.8);

    doc.fillColor("#000000").fontSize(14).text(lrNumber);
    doc
      .fontSize(10)
      .fillColor("#555555")
      .text(`Shipment ${shipment.publicId} · Status ${shipment.status}`);
    doc.moveDown();

    doc.fillColor("#000000").fontSize(11);
    const rows: [string, string][] = [
      ["Consignor / Client", shipment.client || "—"],
      ["Origin", shipment.originLabel || shipment.origin || "—"],
      ["Destination", shipment.destinationLabel || shipment.destination || "—"],
      ["Commodity", shipment.commodity || "—"],
      [
        "Tonnage (MT)",
        Number.isFinite(shipment.tonnageMt) ? String(shipment.tonnageMt) : "—",
      ],
      ["Driver", shipment.driver || shipment.driverId || "Unassigned"],
      ["Vehicle", shipment.vehicle || shipment.vehicleId || "Unassigned"],
      ["Origin type", shipment.originType || "—"],
    ];
    if (shipment.tranzfortId) {
      rows.push(["TranZfort load", shipment.tranzfortId]);
    }

    for (const [label, value] of rows) {
      const y = doc.y;
      doc.fillColor("#666666").text(label, 48, y, { width: 140 });
      doc.fillColor("#000000").text(value, 200, y, { width: 340 });
      doc.moveDown(0.35);
    }

    doc.moveDown(1.2);
    doc
      .fontSize(9)
      .fillColor("#888888")
      .text(
        "This LR is generated from TSM shipment data. Verify weight, seal, and party details before transit.",
      );
    doc.text(`Printed ${new Date().toISOString()}`);

    doc.end();
  });
}
